/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;



public class App {


    public static void main(String[] args) {
        Bitmap coffee = new Bitmap(args[0], args[1], args[2]);




    }
}
