/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;


import java.io.IOException;
import java.nio.file.Paths;

public class App {


    public static void main(String  [] args) throws IOException {
        Bitmap coffee = new Bitmap();
coffee.seeBMPImage("Coffee");



    }
}
